apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repo-front
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Jkvua/frontend-fullstack.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
